version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend_container
    environment:
      DATABASE_URL: postgres://postgres1:postgres1@db:5432/postgres
    ports:
      - "3001:3000" # Port mapping adjusted for backend
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: npm run dev

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  db:
    image: postgres:13
    container_name: db_fullstack
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres1
      POSTGRES_USER: postgres1
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_fullstack
    environment:
      PGADMIN_DEFAULT_EMAIL: "email1@email.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - db
