version: "3.8"

services:
  db:
    image: postgres:13
    container_name: db_fullstack
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres1
      POSTGRES_USER: postgres1
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_fullstack
    environment:
      PGADMIN_DEFAULT_EMAIL: "email1@email.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - db
